;;
;; PDDL file for the AIPS2000 Planning Competition
;; based on the data generated by the airport simulator Astras.
;;

;; Author: Sebastian Trueg thisshouldbethecurrentdateandtime :(
;; Created with PreInstancerDomainExporter 0.6 by Sebastian Trueg <trueg@informatik.uni-freiburg.de>
;;
;; adapted by Kayleigh Sleath to test diagnosis of possible complementary effects (line 46)


(define (domain airport_fixed_structure)

(:requirements :typing :strips)

(:types airplane segment)

(:constants
                seg_pp_0_60
                seg_ppdoor_0_40 - segment

                airplane_CFBEG - airplane
)

(:predicates
                (at-segment ?a - airplane ?s - segment)
                ;; planes are at segments, ie at their end in driving direction

                ;; how the planes affect the airport
                (occupied ?s - segment)
                ;; a plane is in here
                (not_occupied ?s - segment)
                (blocked ?s - segment ?a - airplane)
                ;; segment s is blocked if it is endangered by plane p
                (not_blocked ?s - segment ?a - airplane)
)

(:action possible_complementary_effects

     :parameters (?s_0 - segment ?s_1 - segment)

     :precondition (and)

 ;;POSSIBLE COMPLEMENTARY EFFECTS
     :effect (and 
          (occupied ?s_0)
          (not (occupied ?s_1))
     )
)

(:action move_seg_pp_0_60_seg_ppdoor_0_40_north_north_medium

 :parameters    (?a - airplane)

 :precondition  (and
                 (at-segment ?a seg_pp_0_60)
                 (not_occupied seg_ppdoor_0_40)
                 (not_blocked seg_ppdoor_0_40 airplane_CFBEG)

              )

 :effect        (and
                 (not (occupied seg_pp_0_60))
                 (not_occupied seg_pp_0_60)
                 (not (at-segment ?a seg_pp_0_60))
                 (at-segment ?a seg_ppdoor_0_40)
                )
)
)