;; PDDL file for the AIPS2000 Planning Competition
;; based on the data generated by the airport simulator Astras.

;; Author: Sebastian Trueg thisshouldbethecurrentdateandtime :(
;; Created with PreInstancerDomainExporter 0.6 by Sebastian Trueg <trueg@informatik.uni-freiburg.de>
;;
;; adapted by Kayleigh Sleath to test diagnosis of immutable predicate (line 31)


(define (domain airport_fixed_structure)

(:requirements :typing :strips)

(:types airplane segment)

(:constants
                seg_pp_0_60
                seg_ppdoor_0_40 - segment

                airplane_CFBEG - airplane
)

(:predicates
                (at-segment ?a - airplane ?s - segment)
                ;; planes are at segments, ie at their end in driving direction

                ;;IMMUTABLE PREDICATE
                (not_occupied ?s - segment)
)

(:action move_seg_pp_0_60_seg_ppdoor_0_40_north_north_medium

 :parameters    (?a - airplane)

 :precondition  (and
                 ;;IMMUTABLE PREDICATE IN PRECONDITION 
                 (not_occupied seg_ppdoor_0_40)
                 (at-segment ?a seg_pp_0_60)
              )

 :effect        (and
                 (at-segment ?a seg_ppdoor_0_40)
                )
)
)